<template><div><p>To  improve code quality and reliability involves React-specific best practices, tools, and architectural principles. Below are key strategies tailored for React development:</p>
<h2 id="code-structure-and-best-practices" tabindex="-1"><a class="header-anchor" href="#code-structure-and-best-practices"><span>Code Structure and Best Practices</span></a></h2>
<h3 id="component-design-and-organization" tabindex="-1"><a class="header-anchor" href="#component-design-and-organization"><span>Component Design and Organization</span></a></h3>
<ul>
<li>Follow the Single Responsibility Principle (SRP): Each component should do one thing well.</li>
<li>Use functional components with hooks instead of class components (unless absolutely necessary).</li>
<li>Organize your sources like the follow</li>
</ul>
<div class="language-bash line-numbers-mode" data-ext="bash" data-title="bash"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">src/</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> components/</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">   # Reusable UI components</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> hooks/</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">        # Custom React hooks</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> pages/</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">        # Page-level components</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> context/</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">      # Context providers</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> services/</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">     # API calls and business logic</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> utils/</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">        # Helper functions</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">├──</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> styles/</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">       # Global and module styles</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="hint-container note">
<p class="hint-container-title">Note</p>
<p>Both hooks and services can encapsulate business logic. the diffs are:</p>
<ul>
<li>Services encapsulate business logic that is independent of React. They are purely functional and reusable in any environment—whether in React components, backend scripts, or Node.js CLI tools.</li>
<li>Hooks encapsulate React-specific business logic that needs to manage state, effects, or interact with React’s lifecycle. Hooks make business logic reusable within React components.</li>
</ul>
</div>
<ul>
<li>Keep files small and manageable (~200 lines per file).</li>
<li>Use index files (index.ts) for better imports (import Button from '../components/Button' instead of import Button from '../components/Button/Button').</li>
</ul>
<h3 id="consistent-state-management" tabindex="-1"><a class="header-anchor" href="#consistent-state-management"><span>Consistent State Management</span></a></h3>
<ul>
<li>Use React Context for simple global state (avoid prop drilling).</li>
<li>For complex state management, prefer Redux Toolkit or <RouteLink to="/learn/react/g82ggf3US3YTid/">Zustand</RouteLink> over traditional Redux.</li>
<li>Consider <RouteLink to="/learn/react/zp3FpVXCi7BK7id/">React Query or SWR</RouteLink> for data fetching instead of manual useEffect-based API calls.</li>
</ul>
<h3 id="avoid-unnecessary-re-renders" tabindex="-1"><a class="header-anchor" href="#avoid-unnecessary-re-renders"><span>Avoid Unnecessary Re-renders</span></a></h3>
<ul>
<li>Use React.memo() for pure components.</li>
<li>Use useCallback() and useMemo() to prevent unnecessary recalculations.</li>
<li>Leverage React DevTools Profiler to identify performance bottlenecks.</li>
</ul>
<div class="hint-container note">
<p class="hint-container-title">Note</p>
<p>How to Enabling the Profiler</p>
<ol>
<li><strong>Install React DevTools</strong>: If you haven't already, install the React DevTools browser extension for Chrome or Firefox. It comes built into React Developer Tools for standalone apps.</li>
<li><strong>React Version</strong>: Ensure you're using React 16.5+ for the Profiler to be available.</li>
<li><strong>Profiler Tab</strong>: Open the browser's Developer Tools and navigate to the Profiler tab (next to Components).</li>
</ol>
</div>
<h2 id="type-safety-with-typescript" tabindex="-1"><a class="header-anchor" href="#type-safety-with-typescript"><span>Type Safety with TypeScript</span></a></h2>
<h3 id="define-strict-types-for-props-state-and-function-parameters" tabindex="-1"><a class="header-anchor" href="#define-strict-types-for-props-state-and-function-parameters"><span>Define strict types for props, state, and function parameters.</span></a></h3>
<h3 id="use-react-fc-or-prop-props-to-define-functional-components" tabindex="-1"><a class="header-anchor" href="#use-react-fc-or-prop-props-to-define-functional-components"><span>Use React.FC (or ({ prop }: Props) =&gt; {}) to define functional components.</span></a></h3>
<div class="language-javascript line-numbers-mode" data-ext="javascript" data-title="javascript"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">type</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> ButtonProps</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">  label</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">string</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  onClick</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: () => </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">void</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">};</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Button</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">React</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">FC</span><span style="--shiki-light:#999999;--shiki-dark:#666666">&#x3C;</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">ButtonProps</span><span style="--shiki-light:#999999;--shiki-dark:#666666">> =</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> ({</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> label</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> onClick</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> })</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">  return</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> &#x3C;</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">button</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> onClick</span><span style="--shiki-light:#999999;--shiki-dark:#666666">={</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">onClick</span><span style="--shiki-light:#999999;--shiki-dark:#666666">}>{</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">label</span><span style="--shiki-light:#999999;--shiki-dark:#666666">}&#x3C;/</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">button</span><span style="--shiki-light:#999999;--shiki-dark:#666666">>;</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">};</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="use-discriminated-unions-for-better-prop-management-instead-of-boolean-flags" tabindex="-1"><a class="header-anchor" href="#use-discriminated-unions-for-better-prop-management-instead-of-boolean-flags"><span>Use Discriminated Unions for better prop management instead of boolean flags.</span></a></h3>
<p>Discriminated Unions (also known as tagged unions or sum types) are a feature in some programming languages (like TypeScript, Haskell, and Rust) that allow you to define a type that can hold one of several distinct variants. Each variant is &quot;tagged&quot; with a unique identifier (a discriminator), which makes it easy to distinguish between the different cases at runtime.</p>
<p>Here’s a simple example of a discriminated union in TypeScript</p>
<div class="language-javascript line-numbers-mode" data-ext="javascript" data-title="javascript"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">type</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> Shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  |</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> kind</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">circle</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> radius</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">number</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // Variant 1: Circle</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  |</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> kind</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">square</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> sideLength</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">number</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // Variant 2: Square</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  |</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> kind</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">rectangle</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> width</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">number</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> height</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">number</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> };</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // Variant 3: Rectangle</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> getArea</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">Shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">):</span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994"> number</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">  switch</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> (</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">kind</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    case</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">circle</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">      return</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Math</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">PI</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">radius</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> **</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // Access `radius` safely</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    case</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">square</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">      return</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">sideLength</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> **</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 2</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // Access `sideLength` safely</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    case</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">rectangle</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">      return</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">width</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> *</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">height</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // Access `width` and `height` safely</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    default</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">      // Ensures exhaustiveness: if a new variant is added, TypeScript will throw an error here.</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">      const</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> _exhaustiveCheck</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">never</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">      throw</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> new</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> Error</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">`</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Unknown shape: </span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">${</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">_exhaustiveCheck</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">}</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">`</span><span style="--shiki-light:#999999;--shiki-dark:#666666">);</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  }</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">// Usage</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">const</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> circle</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">Shape</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> kind</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">circle</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965"> radius</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 5</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> };</span></span>
<span class="line"><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">console</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">log</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">getArea</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">circle</span><span style="--shiki-light:#999999;--shiki-dark:#666666">));</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> // 78.53981633974483</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="testing-for-reliability" tabindex="-1"><a class="header-anchor" href="#testing-for-reliability"><span>Testing for Reliability</span></a></h2>
<h3 id="unit-and-integration-testing" tabindex="-1"><a class="header-anchor" href="#unit-and-integration-testing"><span>Unit and Integration Testing</span></a></h3>
<ul>
<li><strong>Use <RouteLink to="/learn/front/UvYWaKydhX/">Jest</RouteLink> and React Testing Library to test components</strong></li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="javascript" data-title="javascript"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> render</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> screen</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">@testing-library/react</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">import</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> Button</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> from</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">./Button</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">test</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">renders button with label</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> ()</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  render</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(&#x3C;</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">Button</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> label</span><span style="--shiki-light:#999999;--shiki-dark:#666666">=</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Click me</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> onClick</span><span style="--shiki-light:#999999;--shiki-dark:#666666">={()</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> =></span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {}}</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> />);</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">  expect</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">screen</span><span style="--shiki-light:#999999;--shiki-dark:#666666">.</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">getByText</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">Click me</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)).</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665">toBeInTheDocument</span><span style="--shiki-light:#999999;--shiki-dark:#666666">();</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">});</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li><strong>Use MSW (Mock Service Worker) for API mocking</strong></li>
</ul>
<h3 id="end-to-end-testing" tabindex="-1"><a class="header-anchor" href="#end-to-end-testing"><span>End-to-End Testing</span></a></h3>
<ul>
<li>Use <RouteLink to="/learn/opensource/1ws3o8/">Cypress</RouteLink> or Playwright for UI testing to simulate real user interactions.</li>
<li>Automate tests in <RouteLink to="/learn/build/q2uqL1id/">CI/CD</RouteLink> pipelines to ensure no breaking changes.</li>
</ul>
<h2 id="maintainability-and-readability" tabindex="-1"><a class="header-anchor" href="#maintainability-and-readability"><span>Maintainability and Readability</span></a></h2>
<h3 id="follow-eslint-and-prettier-with-custom-rules-for-react" tabindex="-1"><a class="header-anchor" href="#follow-eslint-and-prettier-with-custom-rules-for-react"><span>Follow ESLint and Prettier with custom rules for React.</span></a></h3>
<h3 id="use-jsdoc-or-inline-comments-for-complex-logic" tabindex="-1"><a class="header-anchor" href="#use-jsdoc-or-inline-comments-for-complex-logic"><span>Use JSDoc or inline comments for complex logic</span></a></h3>
<div class="language-ts line-numbers-mode" data-ext="ts" data-title="ts"><button class="copy" title="Copy code" data-copied="Copied"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">/**</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> * Fetches user data from the API.</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> * </span><span style="--shiki-light:#999999;--shiki-dark:#666666">@</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">param</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> userId</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> - The ID of the user.</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> * </span><span style="--shiki-light:#999999;--shiki-dark:#666666">@</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">returns</span><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> User data object.</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"> */</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">async</span><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676"> function</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> getUser</span><span style="--shiki-light:#999999;--shiki-dark:#666666">(</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">userId</span><span style="--shiki-light:#999999;--shiki-dark:#666666">: </span><span style="--shiki-light:#2E8F82;--shiki-dark:#5DA994">string</span><span style="--shiki-light:#999999;--shiki-dark:#666666">)</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> {</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> ...</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> }</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="use-storybook-for-documenting-ui-components-interactively" tabindex="-1"><a class="header-anchor" href="#use-storybook-for-documenting-ui-components-interactively"><span>Use Storybook for documenting UI components interactively.</span></a></h3>
<h2 id="security-best-practices" tabindex="-1"><a class="header-anchor" href="#security-best-practices"><span>Security Best Practices</span></a></h2>
<ul>
<li>Sanitize user input using libraries like DOMPurify to prevent XSS attacks.</li>
<li>Use React Error Boundaries to prevent UI crashes</li>
<li>Secure API requests using HTTPS, JWT authentication, and CSRF protection.</li>
</ul>
<h2 id="code-reviews-and-collaboration" tabindex="-1"><a class="header-anchor" href="#code-reviews-and-collaboration"><span>Code Reviews and Collaboration</span></a></h2>
<ul>
<li>
<p>Enforce pull request reviews with a checklist:</p>
<ul>
<li>✅ Code follows ESLint rules</li>
<li>✅ No unnecessary re-renders</li>
<li>✅ Proper TypeScript types used</li>
<li>✅ Has tests for new functionality</li>
</ul>
</li>
<li>
<p>Use <strong>pair programming</strong> for complex features.</p>
</li>
<li>
<p>Encourage team discussions on architecture and best practices.</p>
</li>
</ul>
<div class="hint-container note">
<p class="hint-container-title">Note</p>
<p>Pair programming is a software development practice where two programmers work together at one workstation to complete a task. One person, the driver, writes the code, while the other, the navigator (or observer), reviews each line of code as it is typed. The two programmers switch roles frequently to ensure both are actively engaged and contributing.</p>
</div>
</div></template>


